-- V9: Widen the (Hibernate-auto-generated) CHECK constraint on
-- questions.question_type to allow SHORT_ANSWER.
--
-- The questions table predates any Flyway migration for it — its
-- question_type CHECK constraint was auto-generated by Hibernate
-- (ddl-auto=update) the first time the table was created, listing only the
-- QuestionType enum values that existed at that moment. ddl-auto=update
-- never widens an existing check constraint when the Java enum later gains
-- a new value, so it was silently rejecting every SHORT_ANSWER insert with
-- a generic "violates check constraint" error.
--
-- CODING is intentionally NOT added here — Coding/SQL free-text question
-- authoring was dropped (no sandboxed execution exists to grade them), so
-- CODING is no longer a valid QuestionType at all.
DO $$
DECLARE
  existing_constraint text;
BEGIN
  SELECT con.conname INTO existing_constraint
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  WHERE rel.relname = 'questions'
    AND con.contype = 'c'
    AND att.attname = 'question_type';

  IF existing_constraint IS NOT NULL THEN
    EXECUTE format('ALTER TABLE questions DROP CONSTRAINT %I', existing_constraint);
  END IF;

  ALTER TABLE questions ADD CONSTRAINT questions_question_type_check
    CHECK (question_type IN (
      'MCQ', 'MULTIPLE_CORRECT', 'TRUE_FALSE', 'CODE_OUTPUT', 'DEBUGGING',
      'SCENARIO', 'SQL', 'INTERVIEW', 'SHORT_ANSWER'
    ));
END $$;
