-- V13: Widen the (Hibernate-auto-generated) CHECK constraint on
-- quiz_attempts.status to allow the new INCOMPLETE value.
--
-- Same situation as V11 for questions.question_type: the quiz_attempts
-- table predates any Flyway migration for it, so its status CHECK
-- constraint was auto-generated by Hibernate the first time the table was
-- created, listing only the AttemptStatus enum values that existed at that
-- moment (IN_PROGRESS, SUBMITTED). ddl-auto=update never widens an existing
-- check constraint when the Java enum later gains a new value.
--
-- INCOMPLETE represents an attempt that was started (and so already counts
-- against maxAttempts) but was abandoned before the student submitted or
-- the quiz duration ran out - it can never be resumed.
DO $$
DECLARE
  existing_constraint text;
BEGIN
  SELECT con.conname INTO existing_constraint
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_attribute att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  WHERE rel.relname = 'quiz_attempts'
    AND con.contype = 'c'
    AND att.attname = 'status';

  IF existing_constraint IS NOT NULL THEN
    EXECUTE format('ALTER TABLE quiz_attempts DROP CONSTRAINT %I', existing_constraint);
  END IF;

  ALTER TABLE quiz_attempts ADD CONSTRAINT quiz_attempts_status_check
    CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'INCOMPLETE'));
END $$;
